wagtailnews/urls.py
from django.conf.urls import url

from .views import chooser, editor

app_name = 'wagtailnews'
urlpatterns = [
    url(r'^$', chooser.choose,
        name='choose'),
    url(r'^search/$', chooser.search,
        name='search'),
    url(r'^(?P<pk>\d+)/$', chooser.index,
        name='index'),
    url(r'^(?P<pk>\d+)/create/$', editor.create,
        name='create'),
    url(r'^(?P<pk>\d+)/edit/(?P<newsitem_pk>.*)/$', editor.edit,
        name='edit'),
    url(r'^(?P<pk>\d+)/unpublish/(?P<newsitem_pk>.*)/$', editor.unpublish,
        name='unpublish'),
    url(r'^(?P<pk>\d+)/delete/(?P<newsitem_pk>.*)/$', editor.delete,
        name='delete'),
    url(r'^(?P<pk>\d+)/view_draft/(?P<newsitem_pk>.*)/$', editor.view_draft,
        name='view_draft'),
    # Choosers
    url(r'^chooser/$', chooser.choose_modal, name='chooser'),
    url(r'^chooser/(?P<pk>\d+)/(?P<newsitem_pk>\d+)/$', chooser.chosen_modal, name='chosen'),
]

wagtailnews/templates/wagtailnews/choose.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "News" %}{% endblock %}
{% block bodyclass %}menu-news{% endblock %}
{% block content %}

    {% include "wagtailadmin/shared/header.html" with title="News" icon="news" %}

    <div class="nice-padding">
        {% if has_news %}

            <ul class="listing">
                {% for newsindex, model_type in newsindex_list %}
                    <li>
                        <div class="row row-flush title">
                            <h2>
                                <a href="{% url 'wagtailnews:index' pk=newsindex.pk %}" class="col4">
                                    {{ newsindex.get_admin_display_title }}
                                </a>
                            </h2>
                            <a class="col6" href="{{ newsindex.url }}">{{ newsindex.url }}</a>
                            <small class="col2">{{ model_type|title }}</small>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>There are no news pages yet - go add one!</p>
        {% endif %}
    </div>
{% endblock %}

wagtailnews/templates/wagtailnews/create.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with type=newsitem_opts.verbose_name %}Creating {{ type }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-news{% endblock %}
{% block content %}
    {% trans "New" as new_str %}
    {% trans "news post" as newspost_str %}
    {% include "wagtailadmin/shared/header.html" with title=new_str subtitle=newspost_str icon="news" merged=True %}

    <form action="{% url 'wagtailnews:create' pk=newsindex.pk %}" method="POST">
        {% csrf_token %}
        {{ edit_handler.render_form_content }}

        <footer>
            <ul>
                <li class="actions">
                    <div class="dropdown dropup dropdown-button match-width">
                        <button class="button" type="submit" name="action-draft" value="draft">{% trans 'Save draft' %}</button>
                        <div class="dropdown-toggle icon icon-arrow-up"></div>
                        <ul role="menu">
                            <li><input class="button" type="submit" name="action-publish" value="{% trans 'Publish' %}" /></li>
                        </ul>
                    </div>
                </li>
                <li class="actions preview">
                    <button class="button icon icon-view" name="action-preview" value="woop">
                        {% trans 'Preview' %}
                    </button>
                </li>
            </ul>
        </footer>
    </form>
{% endblock %}

{% block extra_css %}
    {% include "wagtailadmin/pages/_editor_css.html" %}
{% endblock %}
{% block extra_js %}
    {% include "wagtailadmin/pages/_editor_js.html" %}
{% endblock %}

wagtailnews/templates/wagtailnews/delete.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with newsitem=newsitem %}Delete {{ newsitem }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-news{% endblock %}
{% block content %}

    {% trans "Delete" as new_str %}
    {% include "wagtailadmin/shared/header.html" with title=new_str subtitle=newsitem icon="grip" %}

    <div class="row row-flush nice-padding">
        <form action="{% url 'wagtailnews:delete' pk=newsindex.pk newsitem_pk=newsitem.pk %}" method="POST">
            {% csrf_token %}
            <p>{% blocktrans %}Are you sure you want to delete this news item?{% endblocktrans %}</p>
            {% if newsitem.live %}
                <p>{% trans "Alternatively you can unpublish the news item. This removes the news item from public view and you can edit or publish it again later." %}</p>
                <input type="submit" value="{% trans 'Delete it' %}" class="button serious {% if newsitem.live %}button-secondary{% endif %}">
                <a href="{% url 'wagtailnews:unpublish' pk=newsindex.pk newsitem_pk=newsitem.pk %}" class="button">
                    {% trans 'Unpublish it' %}
                </a>
            {% else %}
                <input type="submit" value="{% trans 'Delete it' %}" class="button serious">
            {% endif %}
        </form>
    </div>
{% endblock %}

{% block extra_css %}
    {% include "wagtailadmin/pages/_editor_css.html" %}
{% endblock %}
{% block extra_js %}
    {% include "wagtailadmin/pages/_editor_js.html" %}
{% endblock %}

wagtailnews/templates/wagtailnews/edit.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with newsitem=newsitem type=newsitem_opts.verbose_name %}Editing {{ type }}: {{ newsitem }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-news{% endblock %}
{% block content %}

    {% trans "Edit" as new_str %}
    {% include "wagtailadmin/shared/header.html" with title=new_str subtitle=newsitem icon="news" merged=True %}

    <form action="{% url 'wagtailnews:edit' pk=newsindex.pk newsitem_pk=newsitem.pk %}" method="POST">
        {% csrf_token %}
        {{ edit_handler.render_form_content }}

        <footer>
            <ul>
                <li class="actions">
                    <div class="dropdown dropup dropdown-button match-width">
                        <button class="button" type="submit" name="action-draft" value="draft">{% trans 'Save draft' %}</button>
                        <div class="dropdown-toggle icon icon-arrow-up"></div>
                        <ul role="menu">
                            {% if newsitem.live %}
                                <li><a href="{% url 'wagtailnews:unpublish' pk=newsindex.pk newsitem_pk=newsitem.pk %}" class="button no">{% trans 'Unpublish' %}</a></li>
                            {% endif %}
                            {% if newsitem_perms.delete %}
                                <li><a href="{% url 'wagtailnews:delete' pk=newsindex.pk newsitem_pk=newsitem.pk %}" class="button no">{% trans 'Delete' %}</a></li>
                            {% endif %}
                            <li><hr class="dropdown-separator"></li>
                            <li><input class="button" type="submit" name="action-publish" value="{% trans 'Publish' %}" /></li>
                        </ul>
                    </div>
                </li>
                <li class="actions preview">
                    <button class="button icon icon-view" name="action-preview" value="woop">
                        {% trans 'Preview' %}
                    </button>
                </li>
            </ul>
        </footer>
    </form>
{% endblock %}

{% block extra_css %}
    {% include "wagtailadmin/pages/_editor_css.html" %}
    <style>
        .dropdown-separator {
            border: 0 none;
            height: 1rem;
            display: block;
            background: #333333;
            margin: 0;
        }
    </style>
{% endblock %}
{% block extra_js %}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {% if do_preview %}
    <script>
    $(function() {
        setTimeout(function() {
            var url = "{% url 'wagtailnews:view_draft' pk=newsindex.pk newsitem_pk=newsitem.pk %}";
            var previewWindow = window.open(url, "wagtailnews:edit")
            previewWindow.focus();
        }, 10);
    });
    </script>
    {% endif %}
{% endblock %}

wagtailnews/templates/wagtailnews/index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% load wagtailadmin_tags %}
{% block titletag %}{% trans "News" %}{% endblock %}
{% block bodyclass %}menu-news{% endblock %}
{% block content %}

    <header class="nice-padding merged">
        <div class="row row-flush">
            <div class="left">
                <h1 class="col icon icon-grip">{% blocktrans %}News{% endblocktrans %} <span>{{ newsindex.url }}</span></h1>
                <form class="col search-form" action="" method="GET">
                    <ul class="fields">
                        <li class="required">
                            <div class="field char_field text_input field-small iconfield">
                                <label for="id_q">
                                    Search jobs
                                </label>
                                <div class="field-content">
                                    <div class="input icon-search">
                                        <input id="id_q"
                                              name="q"
                                              value="{{ request.GET.q }}"
                                              placeholder="Search news"
                                              type="text" />
                                        <span></span>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </form>
            </div>
            <div class="right">
                {% if newsitem_perms.add and newsitem_perms.change %}
                    <a href="{% url 'wagtailnews:create' newsindex.pk %}" class="col button bicolor icon icon-plus">{% blocktrans %}Add news post{% endblocktrans %}</a>
                {% endif %}
            </div>
        </div>
    </header>

    {% if newsitem_list %}
        {% include "wagtailnews/newsitem_list.html" %}
        {% paginate page %}
    {% else %}
        <div class="nice-padding">No news posts yet!</div>
    {% endif %}
{% endblock %}

wagtailnews/templates/wagtailnews/newsitem_list.html
{% load i18n %}
{% load wagtailnews_admin_tags %}

<table class="listing full-width">
    <colgroup>
    <thead><tr class="table-headers">
        <th class="title">Title</th>
        <th class="date">Date</th>
        <th class="date">Status</th>
    </tr></thead>
    <tbody>
    {% for newsitem in newsitem_list %}
        <tr>
            <td class="title">
                <h2>
                    {% if newsitem_perms.change %}
                        <a href="{% url 'wagtailnews:edit' pk=newsitem.newsindex_id newsitem_pk=newsitem.pk %}">
                            {{ newsitem }}
                        </a>
                    {% else %}
                        {{ newsitem }}
                    {% endif %}
                </h2>
                <ul class="actions">
                    {% if newsitem_perms.change %}
                        <li><a href="{% url 'wagtailnews:edit' pk=newsitem.newsindex_id newsitem_pk=newsitem.pk %}" class="button button-small">{% trans 'Edit' %}</a></li>
                    {% endif %}
                    <li><a href="{% url 'wagtailnews:view_draft' pk=newsitem.newsindex_id newsitem_pk=newsitem.pk %}" class="button button-small button-secondary">{% trans 'View' %}</a></li>
                    {% if newsitem_perms.delete %}
                        <li><a href="{% url 'wagtailnews:delete' pk=newsitem.newsindex_id newsitem_pk=newsitem.pk %}" class="button button-small button-secondary no">{% trans 'Delete' %}</a></li>
                    {% endif %}
                    {% if newsitem.live and newsitem_perms.change %}
                        <li><a href="{% url 'wagtailnews:unpublish' pk=newsitem.newsindex_id newsitem_pk=newsitem.pk %}" class="button button-small button-secondary no">{% trans 'Unpublish' %}</a></li>
                    {% endif %}
                </ul>
            </td>
            <td class="date" valign="top">
                {{ newsitem.date }}
            </td>
            <td class="status" valign="top">
                {% newsitem_status newsitem %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

wagtailnews/templates/wagtailnews/search.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Search" %}{% endblock %}
{% block bodyclass %}menu-news{% endblock %}
{% block extra-js %}
    <script>
        window.headerSearch = {
            url: "{% url 'wagtailadmin_pages:search' %}",
            termInput: "#id_q",
            targetOutput: "#news-results"
        }
    </script>
{% endblock %}

{% block content %}

    {% trans "Search" as search_str %}

    {% include "wagtailadmin/shared/header.html" with title=search_str search_url="wagtailnews:search" icon="search" %}

    <div id="news-results">
        {% include "wagtailnews/search_results.html" %}
    </div>
{% endblock %}

wagtailnews/templates/wagtailnews/search_results.html
{% load i18n wagtailadmin_tags %}


{% if newsitem_results %}
    <div class="nice-padding">
    {% if single_result_type %}
        <h2>{% blocktrans count counter=newsitem_results.0.2.count %}
            There is one matching news item
        {% plural %}
            There are {{ counter }} matching news items
        {% endblocktrans %}</h2>
    {% else %}
        <h2>News search results</h2>
    {% endif %}

    {% search_other %}
    </div>

    {% for name, newsitem_perms, newsitem_list in newsitem_results %}
    {% if not single_newsitem_model %}
        <div class="nice-padding">
            <h2>{{ name|capfirst }}</h2>
        </div>
    {% endif %}
    {% include "wagtailnews/newsitem_list.html" %}
    {% endfor %}
{% else %}
    <div class="nice-padding">
    {% if query_string %}
        <h2>{% blocktrans %}Sorry, no news items match <em>"{{ query_string }}"</em>{% endblocktrans %}</h2>
        {% search_other %}
    {% else %}
        <p>{% trans 'Enter a search term above' %}</p>
    {% endif %}
    </div>
{% endif %}

wagtailnews/templates/wagtailnews/unpublish.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with newsitem=newsitem %}Unpublish {{ newsitem }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-news{% endblock %}
{% block content %}

    {% trans "Unpublish" as new_str %}
    {% include "wagtailadmin/shared/header.html" with title=new_str subtitle=newsitem icon="grip" %}

    <div class="row row-flush nice-padding">
        <form action="{% url 'wagtailnews:unpublish' pk=newsindex.pk newsitem_pk=newsitem.pk %}" method="POST">
            {% csrf_token %}
            <p>{% blocktrans %}Are you sure you want to unpublish this news item?{% endblocktrans %}</p>
            <input class="button" type="submit" value="{% trans 'Yes, unpublish it' %}">
        </form>
    </div>
{% endblock %}

{% block extra_css %}
    {% include "wagtailadmin/pages/_editor_css.html" %}
{% endblock %}
{% block extra_js %}
    {% include "wagtailadmin/pages/_editor_js.html" %}
{% endblock %}