wagtailnews/urls.py
from django.conf.urls import url

from .views import chooser, editor

app_name = 'wagtailnews'
urlpatterns = [
    url(r'^$', chooser.choose,
        name='choose'),
    url(r'^search/$', chooser.search,
        name='search'),
    url(r'^(?P<pk>\d+)/$', chooser.index,
        name='index'),
    url(r'^(?P<pk>\d+)/create/$', editor.create,
        name='create'),
    url(r'^(?P<pk>\d+)/edit/(?P<newsitem_pk>.*)/$', editor.edit,
        name='edit'),
    url(r'^(?P<pk>\d+)/unpublish/(?P<newsitem_pk>.*)/$', editor.unpublish,
        name='unpublish'),
    url(r'^(?P<pk>\d+)/delete/(?P<newsitem_pk>.*)/$', editor.delete,
        name='delete'),
    url(r'^(?P<pk>\d+)/view_draft/(?P<newsitem_pk>.*)/$', editor.view_draft,
        name='view_draft'),
    # Choosers
    url(r'^chooser/$', chooser.choose_modal, name='chooser'),
    url(r'^chooser/(?P<pk>\d+)/(?P<newsitem_pk>\d+)/$', chooser.chosen_modal, name='chosen'),
]

wagtailnews/views/chooser.py
import json
import logging

from django.apps import apps
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from wagtail.admin.forms import SearchForm
from wagtail.admin.modal_workflow import render_modal_workflow
from wagtail.core.models import Page
from wagtail.search.backends import get_search_backend
from wagtail.utils.pagination import paginate

from ..models import NEWSINDEX_MODEL_CLASSES, AbstractNewsItem, NewsIndexMixin
from ..permissions import (
    perms_for_template, user_can_edit_news, user_can_edit_newsitem)

LOGGER = logging.getLogger(__name__)


def get_allowed_news_types(user):
    """Get a list of all NewsIndex models that the user can edit"""
    return [
        NewsIndex for NewsIndex in NEWSINDEX_MODEL_CLASSES
        if user_can_edit_newsitem(user, NewsIndex.get_newsitem_model())]


def choose(request):
    if not user_can_edit_news(request.user):
        raise PermissionDenied

    allowed_news_types = get_allowed_news_types(request.user)

    allowed_cts = ContentType.objects.get_for_models(*allowed_news_types)\
        .values()
    newsindex_list = Page.objects.filter(content_type__in=allowed_cts).specific()
    newsindex_count = newsindex_list.count()

    if newsindex_count == 1:
        newsindex = newsindex_list.first()
        return redirect('wagtailnews:index', pk=newsindex.pk)

    return render(request, 'wagtailnews/choose.html', {
        'has_news': newsindex_count != 0,
        'newsindex_list': ((newsindex, newsindex.content_type.model_class()._meta.verbose_name)
                           for newsindex in newsindex_list)
    })


def _search_newsitems(request, newsitem_models, query):
    backend = get_search_backend()

    for NewsItem in newsitem_models:
        results = backend.search(query, NewsItem)[:10]
        if results:
            yield (
                NewsItem._meta.verbose_name_plural,
                perms_for_template(request, NewsItem),
                results)


def search(request):
    if not user_can_edit_news(request.user):
        raise PermissionDenied

    allowed_news_types = get_allowed_news_types(request.user)

    query = request.GET.get('q', '')

    # FIXME: this is crap, need to construct a single query for all types
    # to search by relevance however that's not currently possible in
    # a backend agnostic way :(
    newsitem_models = [NewsIndex.get_newsitem_model()
                       for NewsIndex in allowed_news_types]
    newsitem_results = list(_search_newsitems(request, newsitem_models, query))

    return render(request, 'wagtailnews/search.html', {
        'single_result_type': len(newsitem_results) == 1,
        'single_newsitem_model': len(newsitem_models) == 1,
        'newsitem_results': newsitem_results,
        'search_form': SearchForm(request.GET if request.GET else None),
        'query_string': query,
    })


def index(request, pk):
    newsindex = get_object_or_404(
        Page.objects.specific().type(NewsIndexMixin), pk=pk)
    NewsItem = newsindex.get_newsitem_model()

    if not user_can_edit_newsitem(request.user, NewsItem):
        raise PermissionDenied()

    newsitem_list = NewsItem.objects.filter(newsindex=newsindex)

    query = None
    try:
        query = request.GET['q']
    except KeyError:
        pass
    else:
        backend = get_search_backend()
        newsitem_list = backend.search(query, newsitem_list)

    paginator, page = paginate(request, newsitem_list)

    return render(request, 'wagtailnews/index.html', {
        'newsindex': newsindex,
        'page': page,
        'paginator': paginator,
        'newsitem_list': page.object_list,
        'newsitem_perms': perms_for_template(request, NewsItem),
        'query_string': query,
    })


def get_newsitem_model(model_string):
    """
    Get the NewsItem model from a model string. Raises ValueError if the model
    string is invalid, or references a model that is not a NewsItem.
    """
    try:
        NewsItem = apps.get_model(model_string)
        assert issubclass(NewsItem, AbstractNewsItem)
    except (ValueError, LookupError, AssertionError):
        raise ValueError('Invalid news item model string'.format(model_string))
    return NewsItem


def choose_modal(request):
    try:
        newsitem_model_string = request.GET['type']
        NewsItem = get_newsitem_model(newsitem_model_string)
    except (ValueError, KeyError):
        raise Http404

    newsitem_list = NewsItem.objects.all()

    # Search
    is_searching = False
    search_query = None
    if 'q' in request.GET:
        search_form = SearchForm(request.GET, placeholder="Search news")

        if search_form.is_valid():
            search_query = search_form.cleaned_data['q']

            search_backend = get_search_backend()
            newsitem_list = search_backend.search(search_query, newsitem_list)
            is_searching = True

    else:
        search_form = SearchForm()

    # Pagination
    paginator, paginated_items = paginate(request, newsitem_list, per_page=10)

    # If paginating or searching, render "results.html" - these views are
    # accessed via AJAX so do not need the modal wrapper
    if request.GET.get('results', None) == 'true':
        return render(request, "wagtailnews/chooser/search_results.html", {
            'query_string': search_query,
            'items': paginated_items,
            'is_searching': is_searching,
        })

    return render_modal_workflow(
        request,
        'wagtailnews/chooser/chooser.html', 'wagtailnews/chooser/choose.js',
        {
            'query_string': search_query,
            'newsitem_type': newsitem_model_string,
            'items': paginated_items,
            'is_searchable': True,
            'is_searching': is_searching,
            'search_form': search_form,
        }
    )


def chosen_modal(request, pk, newsitem_pk):
    newsindex = get_object_or_404(
        Page.objects.specific().type(NewsIndexMixin), pk=pk)
    NewsItem = newsindex.get_newsitem_model()

    newsitem = get_object_or_404(NewsItem, pk=newsitem_pk)

    return render_modal_workflow(request, None, 'wagtailnews/chooser/chosen.js', {
        'newsitem_json': json.dumps({
            'id': newsitem.id,
            'string': str(newsitem),
            'edit_link': reverse('wagtailnews:edit', kwargs={
                'pk': newsindex.pk, 'newsitem_pk': newsitem.pk}),
        }),
    })

wagtailnews/templates/wagtailnews/chooser/chooser.html
{% load i18n %}
{% trans "Choose a news item" as choose_str %}
{% include "wagtailadmin/shared/header.html" with title=choose_str icon="icon icon-grip" %}

<div class="nice-padding">
	{# Need to keep the form in the HTML, even if it is not searchable #}
	{# This is to allow pagination links to be generated from the form action URL #}
	<form class="newsitem-search search-bar" action="{% url 'wagtailnews:chooser' %}" method="GET">
		{% if is_searchable %}
			<ul class="fields">
				<input type="hidden" name="type" id="id_type" value="{{ newsitem_type }}">
				{% for field in search_form %}
					{% include "wagtailadmin/shared/field_as_li.html" with field=field %}
				{% endfor %}
				<li class="submit"><button class='button' type="submit">Search</button></li>
			</ul>
		{% endif %}
	</form>

	<div id="search-results" class="listing">
		{% include "wagtailnews/chooser/search_results.html" with choosing=1 %}
	</div>
</div>

wagtailnews/templates/wagtailnews/chooser/list.html
{% load i18n %}
{% load wagtailnews_admin_tags %}

<table class="listing">
    <col />
    <col  />
    <col width="16%" />
    <thead>
        <tr class="table-headers">
            <th>{% trans "Title" %}</th>
            <th>{% trans "Status" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for newsitem in items %}
            <tr>
                <td class="title">
                    <h2><a class="newsitem-choice" href="{% url 'wagtailnews:chosen' pk=newsitem.newsindex_id newsitem_pk=newsitem.pk %}">{{ newsitem }}</a></h2>
                </td>
                <td>
                    {% newsitem_status newsitem link=False %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

wagtailnews/templates/wagtailnews/chooser/search_results.html
{% load i18n %}
{% load wagtailadmin_tags %}
{% if items %}
	{% if is_searching %}
		<h2>
		{% blocktrans count counter=items.paginator.count %}
			There is one match
		{% plural %}
			There are {{ counter }} matches
		{% endblocktrans %}
		</h2>
	{% endif %}

	{% include "wagtailnews/chooser/list.html" %}

	{% paginate items %}
{% else %}
	{% if is_searching %}
		 <p>{% blocktrans %}Sorry, no news items match "<em>{{ query_string }}</em>"{% endblocktrans %}</p>
	{% else %}
		{% url 'wagtailnews:create' pk=pk as wagtailnews:create_url %}
		<p class="no-results-message">{% blocktrans %}No {{ newsitem_type_name_plural }} have been created. Why not <a href="{{ wagtailnews:create_url }}">add one</a>?{% endblocktrans %}</p>
	{% endif %}
{% endif %}